init_joint_pos:
  - 0.0
  - 0.0
  - 0.0
  - -60.0
  - 0.0
  - 60.0
  - 45.0

jnt_vals:
  - 0.06092359
  - -0.26931445
  - -0.05046451
  - -1.78810727
  - -0.00984643
  - 1.51733775
  - 0.79647267

arm_speed: 0.1
vel_rate: 100
min_height: 0.37
ee_offset: 0.07  # distance between the target grasp pose and the pre-grasp pose
ori_ctl: true
robot_state: /franka_ros_interface/custom_franka_state_controller/robot_state