init_joint_pos:
  - 0.0
  - 0.0
  - 0.0
  - -60.0
  - 0.0
  - 60.0
  - 45.0
drop_joint_pos:  # degree
  - 0.0
  - 0.0
  - 0.0
  - -60.0
  - 0.0
  - 60.0
  - 45.0

ee_offset: 0.1  # distance between the target grasp pose and the pre-grasp pose